package:
  name: nexus-cat
  version: 0.1.8

source:
  path: .

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - tqdm
    - natsort

test:
  imports:
    - nexus_cat

about:
  home: https://github.com/JulienPerradin/nexus
  license: MIT
  summary: 'Nexus is a Cluster Analysing Toolkit package for atomic systems.'